spring.application.name=loan-application-process
spring.datasource.url=jdbc:postgresql://localhost:5433/loan_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate

# Konfigureerime vanusepiiri vastavalt nõuetele [cite: 33]
loan.validation.max-age=70